name: Go
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Install dependencies
        run: go get ./...
      - name: Static analysis
        run: go vet ./...
      - name: Build binary
        run: CGO_ENABLED=0 go build -o go-ndn-dv cmd/main/main.go
      - name: Test with the Go CLI
        run: go test ./...
